theme: jekyll-theme-hacker
url: "http://bagaturchess.github.io"
baseurl: "/Bagatur"
title: Bagatur
description: Java Chess Engine

# Site Author
author:
  name             : "Krasimir Topchiyski"
  avatar           : "https://github.com/bagaturchess/Bagatur/blob/master/Sources/Resources/bin/engine/logo/bagaturchess9.jpg"
  location         : "Bulgaria"
  email            : "k_topchiyski@yahoo.com"
  facebook         : "Krasimir Topchiyski"
  github           : "bagaturchess"
  linkedin         : "Krasimir Topchiyski"

# SEO Related
google_site_verification : "RJS5kZeQ4MYGu9AVDKlI_y7sf72lrb6epGtnGQCVBMU"
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
  
