theme: jekyll-theme-hacker

url: "http://bagaturchess.github.io/Bagatur/"
baseurl: "/Bagatur"
title: Bagatur Chess Engine in Java
description: The page of Bagatur Chess Engine in Java

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
