theme: jekyll-theme-hacker
url: "http://bagaturchess.github.io"
baseurl: "/Bagatur"
title: Bagatur
description: Java Chess Engine

# Site Author
author:
  name             : "Krasimir Topchiyski"
  avatar           : "https://github.com/bagaturchess/Bagatur/blob/master/Sources/Resources/bin/engine/logo/bagaturchess9.jpg"
  location         : "Bulgaria"
  email            : "k_topchiyski@yahoo.com"
  facebook         : "Krasimir Topchiyski"
  github           : "bagaturchess"
  linkedin         : "Krasimir Topchiyski"

# SEO Related
google_site_verification : "RJS5kZeQ4MYGu9AVDKlI_y7sf72lrb6epGtnGQCVBMU"
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

############# AUTOMATED LINKS #############
# the links.html script requires you to list your sidebars here. this is if you're using managed links (see jekyllhowto-content-and-formatting.html#automatedlinks)
sidebars:
  - generic
  - jekyllhowto

# determines whether the links.html script uses the jurl or hurl values in the sidebar data file
link_type: jurl

sidebar:
    menu:
        home:
            title: "Home"
            url: /
            icon: home
        categories:
            title: "Home"
            url: /
            icon: bookmark
        tags:
            title: "Home"
            url: /
            icon: tags
            
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-avatar
  - jemoji
  - jekyll-mentions
 
